### ISSUE TITLE
Predict Next Purchase Tutorial Code Not working

### ISSUE THREAD

**Issue by SD-HussainAbbas** [alteryx/compose#201]
https://compose.alteryx.com/en/stable/examples/predict_next_purchase.html

from demo.next_purchase import load_sample does not work.

**Comment by jeff-hernandez** [comment]
@SD-HussainAbbas thanks for reaching out! Did you try cloning the repository then running the tutorial? Once you clone the repository and install the [doc requirements](https://github.com/alteryx/compose/blob/main/docs/requirements.txt), you should be able to run the notebook using this command.

```
jupyter notebook docs/source/examples/predict_next_purchase.ipynb
```

Let me know if this solves the issue. Also if you can share the traceback to the error, that would be very helpful.

**Comment by thehomebrewnerd** [comment]
This notebook was recently updated in #275 and is now running properly. As a result, I am going to close out this issue, but feel free to reopen if you are still having trouble.
