### ISSUE TITLE
How to Add Complete Time Range

### ISSUE THREAD

**Issue by S-UP** [alteryx/compose#213]
Within ```label_maker.search()``` there is the option to ```drop_empty=False```. This will allow for Labels like this:

> Event-NoEvent-NoEvent-Event (instead of Event-Event).

I am working with time series data and wonder how to best create the labels so that I get a **complete history** of events from the beginning of say a customer purchasing until **today**.

> Event-NoEvent-NoEvent-Event-NoEvent-NoEvent- ... ... ... NoEvent (today)

Because a customer not transacting provides information as well.

Is there a preferred way to do this in Compose?

**Comment by jeff-hernandez** [comment]
@S-UP thanks for bringing this up! I think this would be a great feature to add. In the search, you can use the `minimum_data` parameter to set the starting point of the time range, but currently, there isn't a parameter to set the stopping point, so it defaults to the last value in the time index. Does it make sense to add a new parameter in the search that allows users to set the stopping point -- perhaps `maximum_data`?

**Comment by S-UP** [comment]
This would make sense to me. It's obviously easy to manipulate the data on my end to achieve the desired output. But I'd prefer if this could be set within Compose so that everything related to creating the labels can be specified there.

**Comment by jeff-hernandez** [comment]
Nice, thanks again for the feature request! I'll keep this issue updated on the progress.

**Comment by jeff-hernandez** [comment]
@S-UP this feature should be available in the next release! Thanks again for the feature request!
