### ISSUE TITLE
Breaking changes in doc tutorials

### ISSUE THREAD

**Issue by jeff-hernandez** [alteryx/compose#224]
The tutorials in the documentation need updating to use the latest API changes from other libraries.

**Comment by gsheni** [comment]
@jeff-hernandez Is there specific libraries that need to be updated? Or it something like AutoML Search from EvalML? What pages does this affect?

**Comment by jeff-hernandez** [comment]
I think this breaking change is related to the switch towards using the Woodwork accessor. The latest doc builds raise an error in this line of the tutorials.

```python
>>> y_pred = y_pred.to_series().values.round() 
...
AttributeError: 'Series' object has no attribute 'to_series'
```
