### ISSUE TITLE
Issue While Running a Example

### ISSUE THREAD

**Issue by HAtheDataScientist** [alteryx/compose#273]
I'm running the example 'Next_Purchase_Prediction' getting an error with the creating entities:
![Screenshot (546)](https://user-images.githubusercontent.com/97654061/149267385-e6dbf81c-1162-497d-a7cd-01b146392d27.png)

**Comment by thehomebrewnerd** [comment]
@HAtheDataScientist The release of Featuretools 1.0 included many breaking changes to the API. We are in process of updating all of our demos and examples to use the new API, but many, including the example you show above, still use the old API. Thank you for bringing this issue to our attention.

It may take a bit of time to get the examples updated, but in the meantime, if you want to try to update this example on your own, you can look through this document that highlights the significant updates that will be required: [Transitioning to Featuretools 1.0](https://featuretools.alteryx.com/en/stable/resources/transition_to_ft_v1.0.html)

**Comment by HAtheDataScientist** [comment]
Hi,
So far I have cracked the error and been able to solve that problem, but
having another issue below,
I am following up with the example Example from compose
<https://compose.alteryx.com/en/stable/examples/predict_next_purchase.html> and
the installed dependencies are from the git doc Dependencies
<https://github.com/alteryx/open_source_demos/blob/main/requirements.txt>.
Getting an issue while running with the evalml, please find the error in
the attachments. I guess there is an error with the older/newer arguments.
please help me with the getting out with the proper Evalml arguments for

**Comment by thehomebrewnerd** [comment]
@HAtheDataScientist I will try to spend a little time updating this example so that it works, but it might take me a day or two.

**Comment by thehomebrewnerd** [comment]
@HAtheDataScientist We released an updated version of compose today that fixes this example. If you install compose 0.8.0, Featuretools 1.4.0, and EvalML 0.41.0, the demo in the updated documentation should now work: https://compose.alteryx.com/en/latest/examples/predict_next_purchase.html

I am going to close out this issue for now, but if you have additional problems, please reopen this issue or create a new issue.
